### ISSUE TITLE
group vars - multiple vars with same name, different value

### ISSUE THREAD

**Issue by seaneon** [alta3/kubernetes-the-alta3-way#1]
https://github.com/alta3/kubernetes-the-alta3-way/blob/1.17/group_vars/all.yml

@sgriffith3 
see lines 25-35
# versions
k8s_version: "1.17.3"
etcd_version: "3.2.17"
cni_version: "0.8.2"
containerd_version: "1.2.6"
cri_tools_version: "1.17.0"
cni_version: "0.8.5"
containerd_version: "1.2.6"
cri_tools_version: "1.13.0"
cfssl_version: "1.3.4"
runc_version: "1.0.0-rc8"

There might be more spots like this.

**Comment by sgriffith3** [comment]
Did this cause this to break? If not, which versions were used?

I see that this could be improved, but please provide some more information on how you would like it to be improved.

**Comment by sgriffith3** [comment]
I removed the following lines. Install still works, and I am able to perform a `kubectl get ns`.
