### ISSUE TITLE
Upgrade to Kubernetes v1.24

### ISSUE THREAD

**Issue by bryfry** [alta3/kubernetes-the-alta3-way#24]
# Kubernetes v1.24.4 - Stargazer

<img src="https://user-images.githubusercontent.com/116113/167276079-2ff62e9e-02a2-449b-9080-5c2cd1bc3ac4.png"  width="400" height="400" />

- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.4
- https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/

**Comment by seaneon** [comment]
You assigning yourself to this one?
