### ISSUE TITLE
Testing: horizontal-scaling-with-kubectl-scale test does not match manifest

### ISSUE THREAD

**Issue by bryfry** [alta3/kubernetes-the-alta3-way#38]
### ⚠️ `horizontal-scaling-with-kubectl-scale`
```bash
student@bchd:~/git/kubernetes-the-alta3-way$ tl horizontal-scaling-with-kubectl-scale
[+] Cleaning cluster
[+] Preparing horizontal-scaling-with-kubectl-scale
[+] Setup complete
[+] Testing horizontal-scaling-with-kubectl-scale
deployment.apps/webservice created
Error from server (NotFound): deployments.apps "sise-deploy" not found
Error from server (NotFound): deployments.apps "sise-deploy" not found
deployment.apps/webservice unchanged
error: the path "deployments/webby-deploy" does not exist
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
webservice   0/3     3            0           1s
Error from server (NotFound): deployments.apps "sise-deploy" not found
[-] Test failed
```

This `test.sh` doesn't match with the supplied manifest `labs/yaml/webby-deploy-filled-out.yaml`

_Originally posted by @bryfry in https://github.com/alta3/kubernetes-the-alta3-way/issues/26#issuecomment-1347688615_

**Comment by bryfry** [comment]
@BicycleWalrus this is an issue outside of the scope of k8s upgrade.  Testing for #37 showed that this `test.sh` is still broken in as reported.

Current version of the test.sh file:
https://github.com/alta3/kubernetes-the-alta3-way/blob/fc1c679c4a0183f722e5e2f2b2f3261f3cf267e7/labs/setup/horizontal-scaling-with-kubectl-scale/test.sh

This setup is referenced in lab: `content/kubernetes/deployments/Horizontal-Scaling-with-kubectl-scale.md`

**Comment by BicycleWalrus** [comment]
Completed
